<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RevitAi.Loader</AssemblyName>
    <RootNamespace>RevitAi</RootNamespace>
    <Version>4.1.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RevitAi.Abstractions\RevitAi.Abstractions.csproj" />
  </ItemGroup>

</Project>

