// <auto-generated>
// Reconstructed compiler-generated anonymous types for RevitAi.Revit.
// ILSpy exported these as empty files because their metadata names begin with angle brackets.
// Shapes recovered from assembly IL: generic parameter order equals property/ctor order.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Text;

internal sealed class _003C_003Ef__AnonymousType7<T0, T1, T2, T3, T4>
{
	private readonly T0 _name;
	private readonly T1 _colorIndex;
	private readonly T2 _isVisible;
	private readonly T3 _isLocked;
	private readonly T4 _lineTypeName;

	public T0 name => _name;
	public T1 colorIndex => _colorIndex;
	public T2 isVisible => _isVisible;
	public T3 isLocked => _isLocked;
	public T4 lineTypeName => _lineTypeName;

	public _003C_003Ef__AnonymousType7(T0 name, T1 colorIndex, T2 isVisible, T3 isLocked, T4 lineTypeName)
	{
		_name = name;
		_colorIndex = colorIndex;
		_isVisible = isVisible;
		_isLocked = isLocked;
		_lineTypeName = lineTypeName;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType7<T0, T1, T2, T3, T4> other) return false;
		return EqualityComparer<T0>.Default.Equals(_name, other._name) && EqualityComparer<T1>.Default.Equals(_colorIndex, other._colorIndex) && EqualityComparer<T2>.Default.Equals(_isVisible, other._isVisible) && EqualityComparer<T3>.Default.Equals(_isLocked, other._isLocked) && EqualityComparer<T4>.Default.Equals(_lineTypeName, other._lineTypeName);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_name), EqualityComparer<T1>.Default.GetHashCode(_colorIndex), EqualityComparer<T2>.Default.GetHashCode(_isVisible), EqualityComparer<T3>.Default.GetHashCode(_isLocked), EqualityComparer<T4>.Default.GetHashCode(_lineTypeName));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("name = ").Append(_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("colorIndex = ").Append(_colorIndex);
		stringBuilder.Append(", ");
		stringBuilder.Append("isVisible = ").Append(_isVisible);
		stringBuilder.Append(", ");
		stringBuilder.Append("isLocked = ").Append(_isLocked);
		stringBuilder.Append(", ");
		stringBuilder.Append("lineTypeName = ").Append(_lineTypeName);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType27<T0, T1, T2>
{
	private readonly T0 _x;
	private readonly T1 _y;
	private readonly T2 _z;

	public T0 x => _x;
	public T1 y => _y;
	public T2 z => _z;

	public _003C_003Ef__AnonymousType27(T0 x, T1 y, T2 z)
	{
		_x = x;
		_y = y;
		_z = z;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType27<T0, T1, T2> other) return false;
		return EqualityComparer<T0>.Default.Equals(_x, other._x) && EqualityComparer<T1>.Default.Equals(_y, other._y) && EqualityComparer<T2>.Default.Equals(_z, other._z);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_x), EqualityComparer<T1>.Default.GetHashCode(_y), EqualityComparer<T2>.Default.GetHashCode(_z));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("x = ").Append(_x);
		stringBuilder.Append(", ");
		stringBuilder.Append("y = ").Append(_y);
		stringBuilder.Append(", ");
		stringBuilder.Append("z = ").Append(_z);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType30<T0, T1, T2, T3, T4, T5, T6, T7>
{
	private readonly T0 _source_element_id;
	private readonly T1 _source_category_name;
	private readonly T2 _source_type_name;
	private readonly T3 _source_family_name;
	private readonly T4 _target_element_id;
	private readonly T5 _target_category_name;
	private readonly T6 _target_type_name;
	private readonly T7 _target_family_name;

	public T0 source_element_id => _source_element_id;
	public T1 source_category_name => _source_category_name;
	public T2 source_type_name => _source_type_name;
	public T3 source_family_name => _source_family_name;
	public T4 target_element_id => _target_element_id;
	public T5 target_category_name => _target_category_name;
	public T6 target_type_name => _target_type_name;
	public T7 target_family_name => _target_family_name;

	public _003C_003Ef__AnonymousType30(T0 source_element_id, T1 source_category_name, T2 source_type_name, T3 source_family_name, T4 target_element_id, T5 target_category_name, T6 target_type_name, T7 target_family_name)
	{
		_source_element_id = source_element_id;
		_source_category_name = source_category_name;
		_source_type_name = source_type_name;
		_source_family_name = source_family_name;
		_target_element_id = target_element_id;
		_target_category_name = target_category_name;
		_target_type_name = target_type_name;
		_target_family_name = target_family_name;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType30<T0, T1, T2, T3, T4, T5, T6, T7> other) return false;
		return EqualityComparer<T0>.Default.Equals(_source_element_id, other._source_element_id) && EqualityComparer<T1>.Default.Equals(_source_category_name, other._source_category_name) && EqualityComparer<T2>.Default.Equals(_source_type_name, other._source_type_name) && EqualityComparer<T3>.Default.Equals(_source_family_name, other._source_family_name) && EqualityComparer<T4>.Default.Equals(_target_element_id, other._target_element_id) && EqualityComparer<T5>.Default.Equals(_target_category_name, other._target_category_name) && EqualityComparer<T6>.Default.Equals(_target_type_name, other._target_type_name) && EqualityComparer<T7>.Default.Equals(_target_family_name, other._target_family_name);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_source_element_id), EqualityComparer<T1>.Default.GetHashCode(_source_category_name), EqualityComparer<T2>.Default.GetHashCode(_source_type_name), EqualityComparer<T3>.Default.GetHashCode(_source_family_name), EqualityComparer<T4>.Default.GetHashCode(_target_element_id), EqualityComparer<T5>.Default.GetHashCode(_target_category_name), EqualityComparer<T6>.Default.GetHashCode(_target_type_name), EqualityComparer<T7>.Default.GetHashCode(_target_family_name));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("source_element_id = ").Append(_source_element_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("source_category_name = ").Append(_source_category_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("source_type_name = ").Append(_source_type_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("source_family_name = ").Append(_source_family_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("target_element_id = ").Append(_target_element_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("target_category_name = ").Append(_target_category_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("target_type_name = ").Append(_target_type_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("target_family_name = ").Append(_target_family_name);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType133<T0, T1, T2, T3>
{
	private readonly T0 _isSuccess;
	private readonly T1 _filePath;
	private readonly T2 _viewName;
	private readonly T3 _error;

	public T0 isSuccess => _isSuccess;
	public T1 filePath => _filePath;
	public T2 viewName => _viewName;
	public T3 error => _error;

	public _003C_003Ef__AnonymousType133(T0 isSuccess, T1 filePath, T2 viewName, T3 error)
	{
		_isSuccess = isSuccess;
		_filePath = filePath;
		_viewName = viewName;
		_error = error;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType133<T0, T1, T2, T3> other) return false;
		return EqualityComparer<T0>.Default.Equals(_isSuccess, other._isSuccess) && EqualityComparer<T1>.Default.Equals(_filePath, other._filePath) && EqualityComparer<T2>.Default.Equals(_viewName, other._viewName) && EqualityComparer<T3>.Default.Equals(_error, other._error);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_isSuccess), EqualityComparer<T1>.Default.GetHashCode(_filePath), EqualityComparer<T2>.Default.GetHashCode(_viewName), EqualityComparer<T3>.Default.GetHashCode(_error));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("isSuccess = ").Append(_isSuccess);
		stringBuilder.Append(", ");
		stringBuilder.Append("filePath = ").Append(_filePath);
		stringBuilder.Append(", ");
		stringBuilder.Append("viewName = ").Append(_viewName);
		stringBuilder.Append(", ");
		stringBuilder.Append("error = ").Append(_error);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType143<T0, T1>
{
	private readonly T0 _category;
	private readonly T1 _count;

	public T0 category => _category;
	public T1 count => _count;

	public _003C_003Ef__AnonymousType143(T0 category, T1 count)
	{
		_category = category;
		_count = count;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType143<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_category, other._category) && EqualityComparer<T1>.Default.Equals(_count, other._count);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_category), EqualityComparer<T1>.Default.GetHashCode(_count));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("category = ").Append(_category);
		stringBuilder.Append(", ");
		stringBuilder.Append("count = ").Append(_count);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType156<T0, T1>
{
	private readonly T0 _type;
	private readonly T1 _count;

	public T0 type => _type;
	public T1 count => _count;

	public _003C_003Ef__AnonymousType156(T0 type, T1 count)
	{
		_type = type;
		_count = count;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType156<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_type, other._type) && EqualityComparer<T1>.Default.Equals(_count, other._count);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_type), EqualityComparer<T1>.Default.GetHashCode(_count));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("type = ").Append(_type);
		stringBuilder.Append(", ");
		stringBuilder.Append("count = ").Append(_count);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType197<T0, T1, T2, T3, T4, T5>
{
	private readonly T0 _unit_type;
	private readonly T1 _display_name;
	private readonly T2 _symbol;
	private readonly T3 _is_metric;
	private readonly T4 _precision;
	private readonly T5 _format_string;

	public T0 unit_type => _unit_type;
	public T1 display_name => _display_name;
	public T2 symbol => _symbol;
	public T3 is_metric => _is_metric;
	public T4 precision => _precision;
	public T5 format_string => _format_string;

	public _003C_003Ef__AnonymousType197(T0 unit_type, T1 display_name, T2 symbol, T3 is_metric, T4 precision, T5 format_string)
	{
		_unit_type = unit_type;
		_display_name = display_name;
		_symbol = symbol;
		_is_metric = is_metric;
		_precision = precision;
		_format_string = format_string;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType197<T0, T1, T2, T3, T4, T5> other) return false;
		return EqualityComparer<T0>.Default.Equals(_unit_type, other._unit_type) && EqualityComparer<T1>.Default.Equals(_display_name, other._display_name) && EqualityComparer<T2>.Default.Equals(_symbol, other._symbol) && EqualityComparer<T3>.Default.Equals(_is_metric, other._is_metric) && EqualityComparer<T4>.Default.Equals(_precision, other._precision) && EqualityComparer<T5>.Default.Equals(_format_string, other._format_string);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_unit_type), EqualityComparer<T1>.Default.GetHashCode(_display_name), EqualityComparer<T2>.Default.GetHashCode(_symbol), EqualityComparer<T3>.Default.GetHashCode(_is_metric), EqualityComparer<T4>.Default.GetHashCode(_precision), EqualityComparer<T5>.Default.GetHashCode(_format_string));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("unit_type = ").Append(_unit_type);
		stringBuilder.Append(", ");
		stringBuilder.Append("display_name = ").Append(_display_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("symbol = ").Append(_symbol);
		stringBuilder.Append(", ");
		stringBuilder.Append("is_metric = ").Append(_is_metric);
		stringBuilder.Append(", ");
		stringBuilder.Append("precision = ").Append(_precision);
		stringBuilder.Append(", ");
		stringBuilder.Append("format_string = ").Append(_format_string);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType199<T0, T1, T2>
{
	private readonly T0 _edge_index;
	private readonly T1 _defines_slope;
	private readonly T2 _slope_angle;

	public T0 edge_index => _edge_index;
	public T1 defines_slope => _defines_slope;
	public T2 slope_angle => _slope_angle;

	public _003C_003Ef__AnonymousType199(T0 edge_index, T1 defines_slope, T2 slope_angle)
	{
		_edge_index = edge_index;
		_defines_slope = defines_slope;
		_slope_angle = slope_angle;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType199<T0, T1, T2> other) return false;
		return EqualityComparer<T0>.Default.Equals(_edge_index, other._edge_index) && EqualityComparer<T1>.Default.Equals(_defines_slope, other._defines_slope) && EqualityComparer<T2>.Default.Equals(_slope_angle, other._slope_angle);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_edge_index), EqualityComparer<T1>.Default.GetHashCode(_defines_slope), EqualityComparer<T2>.Default.GetHashCode(_slope_angle));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("edge_index = ").Append(_edge_index);
		stringBuilder.Append(", ");
		stringBuilder.Append("defines_slope = ").Append(_defines_slope);
		stringBuilder.Append(", ");
		stringBuilder.Append("slope_angle = ").Append(_slope_angle);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType227<T0, T1, T2>
{
	private readonly T0 _type_id;
	private readonly T1 _type_name;
	private readonly T2 _element_type;

	public T0 type_id => _type_id;
	public T1 type_name => _type_name;
	public T2 element_type => _element_type;

	public _003C_003Ef__AnonymousType227(T0 type_id, T1 type_name, T2 element_type)
	{
		_type_id = type_id;
		_type_name = type_name;
		_element_type = element_type;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType227<T0, T1, T2> other) return false;
		return EqualityComparer<T0>.Default.Equals(_type_id, other._type_id) && EqualityComparer<T1>.Default.Equals(_type_name, other._type_name) && EqualityComparer<T2>.Default.Equals(_element_type, other._element_type);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_type_id), EqualityComparer<T1>.Default.GetHashCode(_type_name), EqualityComparer<T2>.Default.GetHashCode(_element_type));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("type_id = ").Append(_type_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("type_name = ").Append(_type_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("element_type = ").Append(_element_type);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType234<T0, T1, T2>
{
	private readonly T0 _Pipe;
	private readonly T1 _DiameterMM;
	private readonly T2 _Step;

	public T0 Pipe => _Pipe;
	public T1 DiameterMM => _DiameterMM;
	public T2 Step => _Step;

	public _003C_003Ef__AnonymousType234(T0 Pipe, T1 DiameterMM, T2 Step)
	{
		_Pipe = Pipe;
		_DiameterMM = DiameterMM;
		_Step = Step;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType234<T0, T1, T2> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Pipe, other._Pipe) && EqualityComparer<T1>.Default.Equals(_DiameterMM, other._DiameterMM) && EqualityComparer<T2>.Default.Equals(_Step, other._Step);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Pipe), EqualityComparer<T1>.Default.GetHashCode(_DiameterMM), EqualityComparer<T2>.Default.GetHashCode(_Step));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Pipe = ").Append(_Pipe);
		stringBuilder.Append(", ");
		stringBuilder.Append("DiameterMM = ").Append(_DiameterMM);
		stringBuilder.Append(", ");
		stringBuilder.Append("Step = ").Append(_Step);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType237<T0, T1, T2, T3>
{
	private readonly T0 _Key;
	private readonly T1 _SortSize;
	private readonly T2 _SizeMM;
	private readonly T3 _Duct;

	public T0 Key => _Key;
	public T1 SortSize => _SortSize;
	public T2 SizeMM => _SizeMM;
	public T3 Duct => _Duct;

	public _003C_003Ef__AnonymousType237(T0 Key, T1 SortSize, T2 SizeMM, T3 Duct)
	{
		_Key = Key;
		_SortSize = SortSize;
		_SizeMM = SizeMM;
		_Duct = Duct;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType237<T0, T1, T2, T3> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Key, other._Key) && EqualityComparer<T1>.Default.Equals(_SortSize, other._SortSize) && EqualityComparer<T2>.Default.Equals(_SizeMM, other._SizeMM) && EqualityComparer<T3>.Default.Equals(_Duct, other._Duct);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Key), EqualityComparer<T1>.Default.GetHashCode(_SortSize), EqualityComparer<T2>.Default.GetHashCode(_SizeMM), EqualityComparer<T3>.Default.GetHashCode(_Duct));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Key = ").Append(_Key);
		stringBuilder.Append(", ");
		stringBuilder.Append("SortSize = ").Append(_SortSize);
		stringBuilder.Append(", ");
		stringBuilder.Append("SizeMM = ").Append(_SizeMM);
		stringBuilder.Append(", ");
		stringBuilder.Append("Duct = ").Append(_Duct);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType239<T0, T1, T2, T3, T4, T5>
{
	private readonly T0 _element_id;
	private readonly T1 _element_type;
	private readonly T2 _diameter_mm;
	private readonly T3 _system_type_id;
	private readonly T4 _length_feet;
	private readonly T5 _length_mm;

	public T0 element_id => _element_id;
	public T1 element_type => _element_type;
	public T2 diameter_mm => _diameter_mm;
	public T3 system_type_id => _system_type_id;
	public T4 length_feet => _length_feet;
	public T5 length_mm => _length_mm;

	public _003C_003Ef__AnonymousType239(T0 element_id, T1 element_type, T2 diameter_mm, T3 system_type_id, T4 length_feet, T5 length_mm)
	{
		_element_id = element_id;
		_element_type = element_type;
		_diameter_mm = diameter_mm;
		_system_type_id = system_type_id;
		_length_feet = length_feet;
		_length_mm = length_mm;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType239<T0, T1, T2, T3, T4, T5> other) return false;
		return EqualityComparer<T0>.Default.Equals(_element_id, other._element_id) && EqualityComparer<T1>.Default.Equals(_element_type, other._element_type) && EqualityComparer<T2>.Default.Equals(_diameter_mm, other._diameter_mm) && EqualityComparer<T3>.Default.Equals(_system_type_id, other._system_type_id) && EqualityComparer<T4>.Default.Equals(_length_feet, other._length_feet) && EqualityComparer<T5>.Default.Equals(_length_mm, other._length_mm);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_element_id), EqualityComparer<T1>.Default.GetHashCode(_element_type), EqualityComparer<T2>.Default.GetHashCode(_diameter_mm), EqualityComparer<T3>.Default.GetHashCode(_system_type_id), EqualityComparer<T4>.Default.GetHashCode(_length_feet), EqualityComparer<T5>.Default.GetHashCode(_length_mm));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("element_id = ").Append(_element_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("element_type = ").Append(_element_type);
		stringBuilder.Append(", ");
		stringBuilder.Append("diameter_mm = ").Append(_diameter_mm);
		stringBuilder.Append(", ");
		stringBuilder.Append("system_type_id = ").Append(_system_type_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("length_feet = ").Append(_length_feet);
		stringBuilder.Append(", ");
		stringBuilder.Append("length_mm = ").Append(_length_mm);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType241<T0, T1, T2, T3, T4, T5, T6>
{
	private readonly T0 _element_id;
	private readonly T1 _element_type;
	private readonly T2 _width_mm;
	private readonly T3 _height_mm;
	private readonly T4 _system_type_id;
	private readonly T5 _length_feet;
	private readonly T6 _length_mm;

	public T0 element_id => _element_id;
	public T1 element_type => _element_type;
	public T2 width_mm => _width_mm;
	public T3 height_mm => _height_mm;
	public T4 system_type_id => _system_type_id;
	public T5 length_feet => _length_feet;
	public T6 length_mm => _length_mm;

	public _003C_003Ef__AnonymousType241(T0 element_id, T1 element_type, T2 width_mm, T3 height_mm, T4 system_type_id, T5 length_feet, T6 length_mm)
	{
		_element_id = element_id;
		_element_type = element_type;
		_width_mm = width_mm;
		_height_mm = height_mm;
		_system_type_id = system_type_id;
		_length_feet = length_feet;
		_length_mm = length_mm;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType241<T0, T1, T2, T3, T4, T5, T6> other) return false;
		return EqualityComparer<T0>.Default.Equals(_element_id, other._element_id) && EqualityComparer<T1>.Default.Equals(_element_type, other._element_type) && EqualityComparer<T2>.Default.Equals(_width_mm, other._width_mm) && EqualityComparer<T3>.Default.Equals(_height_mm, other._height_mm) && EqualityComparer<T4>.Default.Equals(_system_type_id, other._system_type_id) && EqualityComparer<T5>.Default.Equals(_length_feet, other._length_feet) && EqualityComparer<T6>.Default.Equals(_length_mm, other._length_mm);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_element_id), EqualityComparer<T1>.Default.GetHashCode(_element_type), EqualityComparer<T2>.Default.GetHashCode(_width_mm), EqualityComparer<T3>.Default.GetHashCode(_height_mm), EqualityComparer<T4>.Default.GetHashCode(_system_type_id), EqualityComparer<T5>.Default.GetHashCode(_length_feet), EqualityComparer<T6>.Default.GetHashCode(_length_mm));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("element_id = ").Append(_element_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("element_type = ").Append(_element_type);
		stringBuilder.Append(", ");
		stringBuilder.Append("width_mm = ").Append(_width_mm);
		stringBuilder.Append(", ");
		stringBuilder.Append("height_mm = ").Append(_height_mm);
		stringBuilder.Append(", ");
		stringBuilder.Append("system_type_id = ").Append(_system_type_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("length_feet = ").Append(_length_feet);
		stringBuilder.Append(", ");
		stringBuilder.Append("length_mm = ").Append(_length_mm);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType242<T0, T1>
{
	private readonly T0 _thickness;
	private readonly T1 _material;

	public T0 thickness => _thickness;
	public T1 material => _material;

	public _003C_003Ef__AnonymousType242(T0 thickness, T1 material)
	{
		_thickness = thickness;
		_material = material;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType242<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_thickness, other._thickness) && EqualityComparer<T1>.Default.Equals(_material, other._material);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_thickness), EqualityComparer<T1>.Default.GetHashCode(_material));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("thickness = ").Append(_thickness);
		stringBuilder.Append(", ");
		stringBuilder.Append("material = ").Append(_material);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType275<T0, T1, T2, T3>
{
	private readonly T0 _system_type_id;
	private readonly T1 _system_type_name;
	private readonly T2 _system_classification;
	private readonly T3 _abbreviation;

	public T0 system_type_id => _system_type_id;
	public T1 system_type_name => _system_type_name;
	public T2 system_classification => _system_classification;
	public T3 abbreviation => _abbreviation;

	public _003C_003Ef__AnonymousType275(T0 system_type_id, T1 system_type_name, T2 system_classification, T3 abbreviation)
	{
		_system_type_id = system_type_id;
		_system_type_name = system_type_name;
		_system_classification = system_classification;
		_abbreviation = abbreviation;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType275<T0, T1, T2, T3> other) return false;
		return EqualityComparer<T0>.Default.Equals(_system_type_id, other._system_type_id) && EqualityComparer<T1>.Default.Equals(_system_type_name, other._system_type_name) && EqualityComparer<T2>.Default.Equals(_system_classification, other._system_classification) && EqualityComparer<T3>.Default.Equals(_abbreviation, other._abbreviation);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_system_type_id), EqualityComparer<T1>.Default.GetHashCode(_system_type_name), EqualityComparer<T2>.Default.GetHashCode(_system_classification), EqualityComparer<T3>.Default.GetHashCode(_abbreviation));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("system_type_id = ").Append(_system_type_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("system_type_name = ").Append(_system_type_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("system_classification = ").Append(_system_classification);
		stringBuilder.Append(", ");
		stringBuilder.Append("abbreviation = ").Append(_abbreviation);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType291<T0, T1, T2, T3, T4, T5, T6>
{
	private readonly T0 _system_type_id;
	private readonly T1 _system_type_name;
	private readonly T2 _element_type;
	private readonly T3 _total_elements;
	private readonly T4 _insulated_count;
	private readonly T5 _uninsulated_count;
	private readonly T6 _coverage_rate;

	public T0 system_type_id => _system_type_id;
	public T1 system_type_name => _system_type_name;
	public T2 element_type => _element_type;
	public T3 total_elements => _total_elements;
	public T4 insulated_count => _insulated_count;
	public T5 uninsulated_count => _uninsulated_count;
	public T6 coverage_rate => _coverage_rate;

	public _003C_003Ef__AnonymousType291(T0 system_type_id, T1 system_type_name, T2 element_type, T3 total_elements, T4 insulated_count, T5 uninsulated_count, T6 coverage_rate)
	{
		_system_type_id = system_type_id;
		_system_type_name = system_type_name;
		_element_type = element_type;
		_total_elements = total_elements;
		_insulated_count = insulated_count;
		_uninsulated_count = uninsulated_count;
		_coverage_rate = coverage_rate;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType291<T0, T1, T2, T3, T4, T5, T6> other) return false;
		return EqualityComparer<T0>.Default.Equals(_system_type_id, other._system_type_id) && EqualityComparer<T1>.Default.Equals(_system_type_name, other._system_type_name) && EqualityComparer<T2>.Default.Equals(_element_type, other._element_type) && EqualityComparer<T3>.Default.Equals(_total_elements, other._total_elements) && EqualityComparer<T4>.Default.Equals(_insulated_count, other._insulated_count) && EqualityComparer<T5>.Default.Equals(_uninsulated_count, other._uninsulated_count) && EqualityComparer<T6>.Default.Equals(_coverage_rate, other._coverage_rate);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_system_type_id), EqualityComparer<T1>.Default.GetHashCode(_system_type_name), EqualityComparer<T2>.Default.GetHashCode(_element_type), EqualityComparer<T3>.Default.GetHashCode(_total_elements), EqualityComparer<T4>.Default.GetHashCode(_insulated_count), EqualityComparer<T5>.Default.GetHashCode(_uninsulated_count), EqualityComparer<T6>.Default.GetHashCode(_coverage_rate));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("system_type_id = ").Append(_system_type_id);
		stringBuilder.Append(", ");
		stringBuilder.Append("system_type_name = ").Append(_system_type_name);
		stringBuilder.Append(", ");
		stringBuilder.Append("element_type = ").Append(_element_type);
		stringBuilder.Append(", ");
		stringBuilder.Append("total_elements = ").Append(_total_elements);
		stringBuilder.Append(", ");
		stringBuilder.Append("insulated_count = ").Append(_insulated_count);
		stringBuilder.Append(", ");
		stringBuilder.Append("uninsulated_count = ").Append(_uninsulated_count);
		stringBuilder.Append(", ");
		stringBuilder.Append("coverage_rate = ").Append(_coverage_rate);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType315<T0, T1>
{
	private readonly T0 _type;
	private readonly T1 _unit;

	public T0 type => _type;
	public T1 unit => _unit;

	public _003C_003Ef__AnonymousType315(T0 type, T1 unit)
	{
		_type = type;
		_unit = unit;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType315<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_type, other._type) && EqualityComparer<T1>.Default.Equals(_unit, other._unit);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_type), EqualityComparer<T1>.Default.GetHashCode(_unit));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("type = ").Append(_type);
		stringBuilder.Append(", ");
		stringBuilder.Append("unit = ").Append(_unit);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType341<T0, T1>
{
	private readonly T0 _Pipe;
	private readonly T1 _SystemTypeId;

	public T0 Pipe => _Pipe;
	public T1 SystemTypeId => _SystemTypeId;

	public _003C_003Ef__AnonymousType341(T0 Pipe, T1 SystemTypeId)
	{
		_Pipe = Pipe;
		_SystemTypeId = SystemTypeId;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType341<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Pipe, other._Pipe) && EqualityComparer<T1>.Default.Equals(_SystemTypeId, other._SystemTypeId);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Pipe), EqualityComparer<T1>.Default.GetHashCode(_SystemTypeId));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Pipe = ").Append(_Pipe);
		stringBuilder.Append(", ");
		stringBuilder.Append("SystemTypeId = ").Append(_SystemTypeId);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType342<T0, T1>
{
	private readonly T0 _Duct;
	private readonly T1 _SystemTypeId;

	public T0 Duct => _Duct;
	public T1 SystemTypeId => _SystemTypeId;

	public _003C_003Ef__AnonymousType342(T0 Duct, T1 SystemTypeId)
	{
		_Duct = Duct;
		_SystemTypeId = SystemTypeId;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType342<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Duct, other._Duct) && EqualityComparer<T1>.Default.Equals(_SystemTypeId, other._SystemTypeId);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Duct), EqualityComparer<T1>.Default.GetHashCode(_SystemTypeId));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Duct = ").Append(_Duct);
		stringBuilder.Append(", ");
		stringBuilder.Append("SystemTypeId = ").Append(_SystemTypeId);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType348<T0, T1, T2>
{
	private readonly T0 _Face;
	private readonly T1 _Center;
	private readonly T2 _Projection;

	public T0 Face => _Face;
	public T1 Center => _Center;
	public T2 Projection => _Projection;

	public _003C_003Ef__AnonymousType348(T0 Face, T1 Center, T2 Projection)
	{
		_Face = Face;
		_Center = Center;
		_Projection = Projection;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType348<T0, T1, T2> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Face, other._Face) && EqualityComparer<T1>.Default.Equals(_Center, other._Center) && EqualityComparer<T2>.Default.Equals(_Projection, other._Projection);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Face), EqualityComparer<T1>.Default.GetHashCode(_Center), EqualityComparer<T2>.Default.GetHashCode(_Projection));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Face = ").Append(_Face);
		stringBuilder.Append(", ");
		stringBuilder.Append("Center = ").Append(_Center);
		stringBuilder.Append(", ");
		stringBuilder.Append("Projection = ").Append(_Projection);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType349<T0, T1>
{
	private readonly T0 _Thickness;
	private readonly T1 _Material;

	public T0 Thickness => _Thickness;
	public T1 Material => _Material;

	public _003C_003Ef__AnonymousType349(T0 Thickness, T1 Material)
	{
		_Thickness = Thickness;
		_Material = Material;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType349<T0, T1> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Thickness, other._Thickness) && EqualityComparer<T1>.Default.Equals(_Material, other._Material);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Thickness), EqualityComparer<T1>.Default.GetHashCode(_Material));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Thickness = ").Append(_Thickness);
		stringBuilder.Append(", ");
		stringBuilder.Append("Material = ").Append(_Material);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}

internal sealed class _003C_003Ef__AnonymousType351<T0, T1, T2>
{
	private readonly T0 _Floor;
	private readonly T1 _Index;
	private readonly T2 _Area;

	public T0 Floor => _Floor;
	public T1 Index => _Index;
	public T2 Area => _Area;

	public _003C_003Ef__AnonymousType351(T0 Floor, T1 Index, T2 Area)
	{
		_Floor = Floor;
		_Index = Index;
		_Area = Area;
	}

	public override bool Equals(object value)
	{
		if (this == value) return true;
		if (value is not _003C_003Ef__AnonymousType351<T0, T1, T2> other) return false;
		return EqualityComparer<T0>.Default.Equals(_Floor, other._Floor) && EqualityComparer<T1>.Default.Equals(_Index, other._Index) && EqualityComparer<T2>.Default.Equals(_Area, other._Area);
	}

	public override int GetHashCode()
	{
		return HashCode.Combine(EqualityComparer<T0>.Default.GetHashCode(_Floor), EqualityComparer<T1>.Default.GetHashCode(_Index), EqualityComparer<T2>.Default.GetHashCode(_Area));
	}

	public override string ToString()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.Append("{ ");
		stringBuilder.Append("Floor = ").Append(_Floor);
		stringBuilder.Append(", ");
		stringBuilder.Append("Index = ").Append(_Index);
		stringBuilder.Append(", ");
		stringBuilder.Append("Area = ").Append(_Area);
		stringBuilder.Append(" }");
		return stringBuilder.ToString();
	}
}
