// <auto-generated>
// Runtime helper for members whose `ldtoken` ILSpy could not render.
// Names/types were recovered from the assembly IL.
// </auto-generated>
using System;
using System.Linq;
using System.Reflection;
using System.Runtime;

internal static class RuntimeHandleHelper
{
	private const BindingFlags Any =
		BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic;

	internal static RuntimeFieldHandle FieldOf(Type declaringType, string fieldName)
	{
		FieldInfo field = declaringType.GetField(fieldName, Any);
		if (field == null)
		{
			throw new MissingFieldException(declaringType.FullName, fieldName);
		}
		return field.FieldHandle;
	}

	internal static RuntimeMethodHandle MethodOf(Type declaringType, string methodName, int parameterCount)
	{
		MethodInfo method = declaringType
			.GetMethods(Any)
			.FirstOrDefault(m => m.Name == methodName && m.GetParameters().Length == parameterCount);
		if (method == null)
		{
			throw new MissingMethodException(declaringType.FullName, methodName);
		}
		return method.MethodHandle;
	}

	internal static RuntimeMethodHandle CtorOf(Type declaringType, int parameterCount)
	{
		ConstructorInfo ctor = declaringType
			.GetConstructors(Any)
			.FirstOrDefault(c => c.GetParameters().Length == parameterCount);
		if (ctor == null)
		{
			throw new MissingMethodException(declaringType.FullName, ".ctor");
		}
		return ctor.MethodHandle;
	}
}