<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>RevitAi.Main</AssemblyName>
    <RootNamespace>RevitAi</RootNamespace>
    <Version>4.1.0</Version>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RevitAi.Abstractions\RevitAi.Abstractions.csproj" />
    <ProjectReference Include="..\RevitAi.Core\RevitAi.Core.csproj" />
  </ItemGroup>

</Project>

